# Generated by Django 4.0.3 on 2022-03-24 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mydateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='my_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
